[package]
name = "blockzilla-read-indexer-v3"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[[bin]]
name = "read-indexer-v3"
path = "src/main.rs"

[dependencies]
blockzilla-dump = { path = "../../crates/blockzilla-dump" }
blockzilla-indexer-v3-read-sdk = { path = "../../crates/blockzilla-indexer-v3-read-sdk" }
blockzilla-example-workloads = { path = "../../crates/blockzilla-example-workloads" }
blockzilla-query-sdk = { path = "../../crates/blockzilla-query-sdk" }
bs58 = "0.5.1"

[lints]
workspace = true
