[package]
name = "old-faithful-get-block"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
anyhow = "1.0.104"
base64 = "0.23.1"
base58-turbo = "0.3.0"
five8 = "1.0.0"
js-sys = "0.3.105"
of-car-reader = { path = "../../crates/old-faithful/of-car-reader", version = "=0.2.0", default-features = false, features = ["compact-index", "zstd-wasm"] }
of-slot-ranges = { path = "../../crates/old-faithful/of-slot-ranges", default-features = false }
prost = "0.14.4"
quick-protobuf = "0.8.1"
ryu = "1.0.23"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
wasm-bindgen = "0.2.128"
wincode = "=0.6.1"
worker = { version = "0.8.5", features = ["http"] }

[lints]
workspace = true
