[package]
name = "blockzilla-compact-v2-read-sdk"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "High-level network and local reader for Blockzilla Compact V2 epochs"
readme = "README.md"
include = ["Cargo.toml", "README.md", "src/**"]
keywords = ["solana", "archive", "streaming", "indexer"]
categories = ["database", "filesystem"]

[dependencies]
blockzilla-format = { version = "0.2.0", path = "../blockzilla-format" }
blockzilla-query-sdk = { version = "0.2.0", path = "../blockzilla-query-sdk" }
blockzilla-read-sdk = { version = "0.2.0", path = "../blockzilla-read-sdk", features = ["http"] }
sha2 = "0.11.0"
thiserror = "2.0.18"
url = "2.5.8"

[dev-dependencies]
tempfile = "3.27.0"
