[package]
name = "blockzilla-compact"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false
autobins = false
description = "Compact record model: blocks, transactions, metadata and logs"

[features]
default = ["known-program-logs"]
known-program-logs = ["blockzilla-program-logs/known-program-logs"]

[dependencies]
blockzilla-primitives = { path = "../../blockzilla-primitives" }
blockzilla-registry = { path = "../blockzilla-registry" }
blockzilla-program-logs = { path = "../../parser/blockzilla-program-logs", default-features = false }
anyhow = "1.0.104"
data-encoding = "2.11.1"
heapless = { version = "0.9.3", features = ["serde"] }
prost = "0.14.4"
serde = { version = "1.0.229", features = ["derive"] }
solana-pubkey = "4.2.1"
wincode = { version = "=0.6.1", features = ["derive"] }
of-car-reader = { path = "../../old-faithful/of-car-reader", version = "0.2.0", default-features = false }
blockzilla-log-parser = { path = "../../parser/blockzilla-log-parser" }

[lints]
workspace = true
