[package]
name = "blockzilla-source-cache"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Persistent HTTP object cache"

[dependencies]
blockzilla-source = { version = "0.2.0", path = "../blockzilla-source" }
blockzilla-source-http = { version = "0.2.0", path = "../blockzilla-source-http" }
rustix = { version = "1.1.4", features = ["fs"] }

[dev-dependencies]
tempfile = "3.24.0"

[lints]
workspace = true
