name = "of-get-block-worker"
main = "build/index.js"
compatibility_date = "2026-05-18"

[[r2_buckets]]
binding = "OF_INDEXES"
bucket_name = "blockzilla"

[build]
command = "cargo install -q worker-build && worker-build --release ."

[observability]
[observability.logs]
enabled = true
invocation_logs = true
