name = "cloudflare-solana-rpc"
main = "build/index.js"
compatibility_date = "2026-05-18"

[build]
command = "cargo install -q worker-build && worker-build --release . --no-default-features --features worker"

[[r2_buckets]]
binding = "SLOT_RANGES"
bucket_name = "blockzilla"

[vars]
OF_SLOT_INDEX_SOURCE = "r2"
OF_ARCHIVE_SOURCE = "http"
OF_ARCHIVE_BASE_URL = "https://files.old-faithful.net"

[observability]
[observability.logs]
enabled = true
invocation_logs = true
