[package]
name = "blockzilla-indexer-v3-read-sdk"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false
description = "High-level targeted reader for Blockzilla Indexer V3 archives"
readme = "README.md"

[dependencies]
blockzilla-source = { version = "0.2.0", path = "../source/blockzilla-source" }
blockzilla-source-local = { version = "0.2.0", path = "../source/blockzilla-source-local" }
blockzilla-source-http = { version = "0.2.0", path = "../source/blockzilla-source-http" }
blockzilla-source-cache = { version = "0.2.0", path = "../source/blockzilla-source-cache" }
anyhow = "1.0.100"
blockzilla-firebase-indexer = { path = "../blockzilla-firebase-indexer" }
blockzilla-query-sdk = { version = "0.2.0", path = "../blockzilla-query-sdk" }
sha2 = "0.11.0"
thiserror = "2.0.18"
url = "2.5.8"

[dev-dependencies]
tempfile = "3.23.0"

[lints]
workspace = true
