[package]
name = "blockzilla-live-format"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false
autobins = false
description = "Block candidate and pre-hot live block formats"

[features]
default = ["known-program-logs"]
known-program-logs = [
    "blockzilla-archive-v2/known-program-logs",
    "blockzilla-compact/known-program-logs",
]

[dependencies]
blockzilla-archive-v2 = { path = "../blockzilla-archive-v2", default-features = false }
blockzilla-compact = { path = "../blockzilla-compact", default-features = false }
serde = { version = "1.0.228", features = ["derive"] }
wincode = { version = "=0.6.1", features = ["derive"] }

[dev-dependencies]
blockzilla-primitives = { path = "../blockzilla-primitives" }

[lints]
workspace = true
