[package]
name = "blockzilla-replay"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Replay-first Solana runtime experiments for Blockzilla"

[[bin]]
name = "blockzilla-replay-poc"
path = "src/main.rs"
required-features = ["genesis"]

[[bin]]
name = "extract-unsupported-program"
path = "src/bin/extract-unsupported-program.rs"

[features]
default = ["genesis"]
genesis = []

[dependencies]
anyhow = "1.0.102"
base64 = "0.22.1"
blockzilla-format = { path = "../blockzilla-format" }
blockzilla-read-sdk = { path = "../blockzilla-read-sdk" }
bzip2 = "0.5.2"
bs58 = "0.5.1"
clap = { version = "4.6.1", features = ["derive"] }
curve25519-dalek = "=5.0.0"
hashbrown = "0.15.5"
object = { version = "0.37.3", default-features = false, features = ["elf", "read_core"] }
pprof = { version = "0.15.0", features = ["flamegraph"] }
rayon = "1.11.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
sha2 = "0.11.0"
smallvec = "1.15.1"
solana-sbpf = "=0.21.0"
target-lexicon = "=0.13.5"
tar = "0.4.43"
thiserror = "2.0.18"
wincode = { version = "=0.6.1", features = ["derive", "smallvec"] }

[target.'cfg(target_arch = "aarch64")'.dependencies]
cranelift-codegen = "=0.134.2"
cranelift-frontend = "=0.134.2"
cranelift-jit = "=0.134.2"
cranelift-module = "=0.134.2"
cranelift-native = "=0.134.2"
